"""Representative tasks based on the user's recurring real workflows."""

INITIAL_CASES = (
    ("更新 TTD", "luna"),
    ("更新 TTT", "luna"),
    ("Docker 容器按现有 compose 流程做常规更新", "luna"),
    ("查看 TTD 容器日志", "luna"),
    ("查询当前 Codex CLI 版本", "luna"),
    ("修改一个配置字段，把超时时间改成 30 秒", "luna"),
    ("简单 CSS 修改：把按钮颜色改成蓝色", "luna"),
    ("执行已有的 ttd-compose-update 脚本", "luna"),
    ("按照固定 SOP 处理这批质检数据", "luna"),
    ("整理下载目录里的文件", "luna"),
    ("查看 Clash 当前运行状态", "luna"),
    ("这个规则现在可以使用了吗？", "luna"),
    ("我现在会话设定的是 Luna xhigh，请求会先经过 Router 判断，是吗？", "luna"),
    ("你说的原生 Codex TUI 是什么意思？", "luna"),
    ("Jev 和当前规则版有什么区别？", "luna"),
    ("请简单说明当前实际使用的是哪个模型", "luna"),
    ("按刚才已经确认的方案开始执行修改并验证结果", "luna"),
    ("方案已经定稿，开始实施并修改多个文件", "luna"),
    ("按上述方案修复认证问题，不需要重新分析", "luna"),
    ("分析 TTD 到 Mihomo 的 RE0 转存为什么失败", "sol"),
    ("排查 Codex Remote WebSocket 一直 Errored 的根因", "sol"),
    ("分析 Tailscale 出口流量为什么没有经过 Clash TUN", "sol"),
    ("设计 APK 修改方案并评估车机兼容风险", "sol"),
    ("制定视频审核系统的质检规则和验收方案", "sol"),
    ("重构多个网页模块并处理前后端调用链", "sol"),
    ("比较两种 Codex 模型路由方案的长期维护成本", "sol"),
    ("优化一下这个系统", "sol"),
    ("删除生产数据库中的全部数据", "sol"),
    ("分析 Emby 黑屏涉及 TTD、STRM 和播放器哪一层", "sol"),
    ("为什么 Codex Router 最近频繁崩溃？请排查根因", "sol"),
    ("判断这个 Router 架构是否能支持多系统联动，并评估风险", "sol"),
    ("按上述方案执行，但先重新评估认证风险并排查失败原因", "sol"),
    ("按已确认方案删除生产数据库中的全部数据", "sol"),
    ("设计大型跨系统迁移架构，要求零停机、容灾和完整回滚", "astra"),
    ("全量重构 TTD、Mihomo、Caddy、Emby 和 Tailscale 多套系统联动架构", "astra"),
    ("为 Codex Desktop、CLI、IDE 设计极复杂端到端 Router 长链路架构", "astra"),
)


ESCALATION_CASES = (
    ("Luna 第一次执行失败", "luna", 1, False, False, "luna"),
    ("Luna 连续两次执行失败", "luna", 2, False, False, "sol"),
    ("Luna 重复同一认证错误", "luna", 1, True, False, "sol"),
    ("Luna 发现任务范围扩大到多个服务", "luna", 0, False, True, "sol"),
    ("Sol 尚未达到升级条件", "sol", 1, False, False, "sol"),
    ("Sol 多次失败仍未解决", "sol", 2, False, False, "astra"),
    ("Astra 不自动降级", "astra", 0, False, False, "astra"),
)
